apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "sumologic.metadata.name.roles.clusterrole" . }}
  labels:
    app: {{ template "sumologic.labels.app.roles.clusterrole" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
rules:
- apiGroups: ["", "apps", "extensions", "events.k8s.io"]
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - configmaps
  verbs: ["create", "patch"]
{{- if .Values.fluentd.podSecurityPolicy.create }}
- apiGroups: ["policy"]
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "sumologic.metadata.name.events.statefulset" . }}
  - {{ template "sumologic.metadata.name.metrics.statefulset" . }}
  - {{ template "sumologic.metadata.name.logs.statefulset" . }}
  verbs: ["use"]
{{- end }}
{{- if index .Values "opentelemetry-operator" "enabled" }}
- apiGroups: ["opentelemetry.io"]
  resources:
  - instrumentations
  verbs: ["patch", "get", "create"]
{{- end }}
