apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.fluentdUserConfig.fullname" . }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{ template "sumologic.labels.common" . }}
data:
  fluent.conf: |-
    @include common.conf
    @include metrics.conf
    @include logs.conf
  {{- (tpl (.Files.Glob "conf/*.conf").AsConfig .) | nindent 2 }}
  {{- (tpl (.Files.Glob "conf/metrics/*.conf").AsConfig .) | nindent 2 }}
  {{- (tpl (.Files.Glob "conf/logs/*.conf").AsConfig .) | nindent 2 }}
