apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.fullname" . }}-fluentd
  labels:
    app: {{ template "sumologic.labels.app" . }}-fluentd
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  fluent.conf: |-
{{- .Values.fluentd.rawConfig | nindent 4 }}
{{- if .Values.sumologic.traces.enabled }}
    @include traces.conf
{{- end }}
{{- (tpl (.Files.Glob "conf/*.conf").AsConfig .) | nindent 2 }}
{{- (tpl (.Files.Glob "conf/logs/*.conf").AsConfig .) | nindent 2 }}
{{- if .Values.sumologic.traces.enabled }}
{{- (tpl (.Files.Glob "conf/traces/*.conf").AsConfig .) | nindent 2 }}
{{- end }}