{{- if eq .Values.fluentd.events.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-events" (include "sumologic.fullname" .) }}
  labels:
    app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "sumologic.fullname" . }}
{{- if .Values.eventsDeployment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.eventsDeployment.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.eventsDeployment.tolerations }}
      tolerations:
{{ toYaml .Values.eventsDeployment.tolerations | indent 8 }}
{{- end }}
      volumes:
      - name: pos-files
        hostPath:
          path: /var/run/fluentd-pos
          type: ""
      - name: config-volume
        configMap:
          name: {{ printf "%s-events" (include "sumologic.fullname" .) }}
      containers:
      - name: fluentd-events
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.eventsDeployment.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
        - name: pos-files
          mountPath: /mnt/pos/
        livenessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "[ $(pgrep ruby | wc -l) -gt 0 ]"
          initialDelaySeconds: 300
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "[ $(pgrep ruby | wc -l) -gt 0 ]"
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
        - name: SUMO_ENDPOINT_EVENTS
          valueFrom:
            secretKeyRef:
              name: sumologic
              key: endpoint-events
{{- end }}