{{- if eq .Values.fluentd.events.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-events-fluentd" (include "sumologic.fullname" .) }}
  labels:
    app: {{ printf "%s-events-fluentd" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    app: {{ printf "%s-events-fluentd" (include "sumologic.labels.app" .) }}
  ports:
  - name: metrics
    port: 24231
    targetPort: 24231
    protocol: TCP
{{- end }}