{{- if eq .Values.fluentd.events.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-events" (include "sumologic.fullname" .) }}
  labels:
    app: {{ printf "%s-events" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  fluent.conf: |-
    @include events.conf
  {{- (tpl (.Files.Glob "conf/events/*.conf").AsConfig .) | nindent 2 }}
  {{- (tpl (.Files.Glob "conf/buffer.output.conf").AsConfig .) | nindent 2 }}
{{- end }}