{{- if .Values.fluentd.metrics.autoscaling.enabled}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sumologic.metadata.name.metrics" . }}
  labels:
    app: {{ template "sumologic.labels.app.metrics" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "sumologic.metadata.name.metrics.statefulset" . }}
  minReplicas: {{ .Values.fluentd.metrics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fluentd.metrics.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.fluentd.metrics.autoscaling.targetCPUUtilizationPercentage }}
{{- end -}}
