apiVersion: v1
kind: Service
metadata:
  name: {{ template "sumologic.metadata.name.metrics.service-headless" . }}
  labels:
    app: {{ template "sumologic.labels.app.metrics.service-headless" . }}
    {{- include "sumologic.labels.events" . | nindent 4 }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    app: {{ template "sumologic.labels.app.metrics.pod" . }}
  clusterIP: None
  ports:
  - name: prom-write
    port: 9888
    targetPort: 9888
    protocol: TCP
  - name: metrics
    port: 24231
    targetPort: 24231
    protocol: TCP
