apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.fullname" . }}-fluentd-metrics
  labels:
    app: {{ template "sumologic.labels.app" . }}-fluentd-metrics
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  fluent.conf: |-
{{- .Values.fluentd.metricsRawConfig | nindent 4 }}
{{- (tpl (.Files.Glob "conf/*.conf").AsConfig .) | nindent 2 }}
{{- (tpl (.Files.Glob "conf/metrics/*.conf").AsConfig .) | nindent 2 }}