apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.metadata.name.metrics.configmap" . }}
  labels:
    app: {{ template "sumologic.labels.app.metrics" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  fluent.conf: |-
{{- .Values.fluentd.metrics.rawConfig | nindent 4 }}
{{- (tpl (.Files.Glob "conf/*.conf").AsConfig .) | nindent 2 }}
{{- (tpl (.Files.Glob "conf/metrics/*.conf").AsConfig .) | nindent 2 }}