apiVersion: v1
kind: Service
metadata:
  name: {{ template "sumologic.fullname" . }}-fluentd
  labels:
    app: {{ template "sumologic.labels.app" . }}-fluentd
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    app: {{ template "sumologic.labels.app" . }}-fluentd
  ports:
  {{- if .Values.sumologic.traces.enabled }}
  - name: zipkin-write
    port: 9411
    targetPort: 9411
    protocol: TCP
  {{- end }}
  - name: fluent-bit
    port: 24321
    targetPort: 24321
    protocol: TCP
  - name: metrics
    port: 24231
    targetPort: 24231
    protocol: TCP
