{{ $tracesSampler := .Values.tracesSampler }}
{{ $tracesEnabled := .Values.sumologic.traces.enabled }}
{{- if $tracesEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sumologic.metadata.name.tracessampler.deployment" . }}
  namespace: {{ template "sumologic.namespace"  . }}
  labels:
    app: {{ template "sumologic.labels.app.tracessampler.deployment" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: {{ $tracesSampler.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ template "sumologic.labels.app.tracessampler.pod" . }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 6 }}
{{- end }}
{{- if $tracesSampler.deployment.podLabels }}
{{ toYaml $tracesSampler.deployment.podLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/instrumentation/traces-sampler/configmap.yaml") . | sha256sum }}
{{- if .Values.sumologic.podAnnotations }}
{{ toYaml .Values.sumologic.podAnnotations | indent 8 }}
{{- end }}
{{- if $tracesSampler.deployment.podAnnotations }}
{{ toYaml $tracesSampler.deployment.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "sumologic.labels.app.tracessampler.pod" . }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 8 }}
{{- end }}
{{- if $tracesSampler.deployment.podLabels }}
{{ toYaml $tracesSampler.deployment.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "sumologic.metadata.name.roles.serviceaccount" . }}
{{- if not (empty (include "tracesSampler.deployment.nodeSelector" .)) }}
      nodeSelector:
{{ include "tracesSampler.deployment.nodeSelector" . | indent 8 }}
{{- end }}
{{- if not (empty (include "tracesSampler.deployment.tolerations" .)) }}
      tolerations:
{{ include "tracesSampler.deployment.tolerations" . | indent 8 }}
{{- end }}
      {{- if $tracesSampler.deployment.priorityClassName }}
      priorityClassName: {{ $tracesSampler.deployment.priorityClassName | quote }}
      {{- end }}
      containers:
      - name: otelcol
        image: {{ template "sumologic.tracessampler.image" . }}
        imagePullPolicy: {{ $tracesSampler.deployment.image.pullPolicy }}
        args:
          - --config=/conf/traces.sampler.conf.yaml
        env:
        - name: GOGC
          value: "80"
{{- $ctx := .Values -}}
{{- include "kubernetes.sources.envs" (dict "Context" $ctx "Type" "traces") | nindent 8 -}}
{{- include "proxy-env-variables" . | nindent 8 -}}
{{- if $tracesSampler.deployment.extraEnvVars }}
{{- toYaml $tracesSampler.deployment.extraEnvVars | nindent 8 }}
{{- end }}
        resources:
          {{- toYaml $tracesSampler.deployment.resources | nindent 10 }}
        ports:
        - name: pprof
          containerPort: 1777
          protocol: TCP
        - containerPort: 5778  # Default endpoint for Jaeger Sampling.
        - containerPort: 6831  # Default endpoint for Jaeger Thrift Compact receiver.
          protocol: UDP
        - containerPort: 6832  # Default endpoint for Jaeger Thrift Binary receiver.
          protocol: UDP
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 9411  # Default endpoint for Zipkin receiver.
        - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
        - containerPort: 14267 # Default endpoint for Jaeger TChannel receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 55678 # Default endpoint for Opencensus receiver.
        - containerPort: 4317  # Default endpoint for OTLP gRPC receiver.
        - containerPort: 4318  # Default endpoint for OTLP HTTP receiver.
        - containerPort: 55680 # Old endpoint for OTLP gRPC receiver.
        - containerPort: 55681 # Default endpoint for OTLP HTTP receiver. (deprecated)
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        - name: tmp
          mountPath: /tmp
{{- if $tracesSampler.persistence.enabled }}
        - name: file-storage
          mountPath: {{ $tracesSampler.persistence.persistentVolume.path }}
{{- end}}
{{- if $tracesSampler.deployment.extraVolumeMounts }}
{{- toYaml $tracesSampler.deployment.extraVolumeMounts | nindent 8 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: {{ template "sumologic.metadata.name.tracessampler.configmap" . }}
          name: otel-collector-config-vol
        - name: tmp
          emptyDir: {}
{{- if $tracesSampler.persistence.enabled }}
        - name: file-storage
          mountPath: {{ $tracesSampler.persistence.persistentVolume.path }}
{{- end }}
{{- if $tracesSampler.deployment.extraVolumes }}
{{- toYaml $tracesSampler.deployment.extraVolumes | nindent 8 }}
{{- end }}
{{- if $tracesSampler.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: file-storage
{{- if $tracesSampler.persistence.pvcLabels }}
      labels:
{{ toYaml $tracesSampler.persistence.pvcLabels | indent 8 }}
{{- end }}
    spec:
      accessModes: [{{ $tracesSampler.persistence.accessMode }}]
      storageClassName: {{ $tracesSampler.persistence.storageClass }}
      resources:
        requests:
          storage: {{ $tracesSampler.persistence.size }}
{{- end }}
{{- end }}
