dependencies:
  - name: fluent-bit
    version: 2.8.14
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled,sumologic.logs.enabled
  - name: prometheus-operator
    version: 8.13.8
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-operator.enabled,sumologic.metrics.enabled
  - name: falco
    version: 1.1.8
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled
  - name: metrics-server
    version: 2.11.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
  - name: telegraf-operator
    alias: telegraf
    version: 1.1.2
    repository: https://helm.influxdata.com/
    condition: telegraf.enabled
