dependencies:
  - name: fluent-bit
    version: 2.8.14
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled
  - name: prometheus-operator
    version: 8.13.8
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-operator.enabled
  - name: falco
    version: 1.1.8
    repository: https://falcosecurity.github.io/c
    condition: falco.enabled
  - name: metrics-server
    version: 2.11.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
