dependencies:
  - name: fluent-bit
    version: 2.8.14
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled
  - name: prometheus-operator
    version: 8.13.8
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluentd.metrics.enabled
  - name: falco
    version: 1.1.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: falco.enabled
  - name: metrics-server
    version: 2.11.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
