dependencies:
  - name: fluent-bit
    version: 2.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled
  - name: prometheus-operator
    version: 8.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-operator.enabled
  - name: falco
    version: 1.1.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: falco.enabled
  - name: metrics-server
    version: 2.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
