dependencies:
  - name: fluent-bit
    version: 2.10.1
    repository: https://charts.helm.sh/stable
    condition: fluent-bit.enabled,sumologic.logs.enabled
  - name: kube-prometheus-stack
    version: 9.3.4
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus-operator
    condition: prometheus-operator.enabled,sumologic.metrics.enabled
  - name: falco
    version: 1.5.4
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled
  - name: metrics-server
    version: 4.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: metrics-server.enabled
  - name: telegraf-operator
    version: 1.1.6
    repository: https://sumologic.github.io/influxdata-helm-charts
    condition: telegraf-operator.enabled
