dependencies:
  - name: fluent-bit
    version: 2.10.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluent-bit.enabled,sumologic.logs.enabled
  - name: prometheus-operator
    version: 8.13.8
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus-operator.enabled,sumologic.metrics.enabled
  - name: falco
    version: 1.4.0
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled
  - name: metrics-server
    version: 2.11.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
  - name: telegraf-operator
    version: 1.1.4
    repository: https://sumologic.github.io/influxdata-helm-charts
    condition: telegraf-operator.enabled
