{{- if .Values.sumologic.cleanupEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "sumologic.metadata.name.cleanup.roles.serviceaccount" . }}
  annotations:
{{ include "sumologic.annotations.app.cleanup.helmsh" "0" | indent 4 }}
{{- with .Values.sumologic.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    app: {{ template "sumologic.labels.app.cleanup.roles.serviceaccount" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- end }}
