{{- if .Values.sumologic.setupEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.metadata.name.setup.configmap" . }}
  namespace: {{ template "sumologic.namespace" . }}
  annotations:
{{ include "sumologic.annotations.app.setup.helmsh" "2" | indent 4 }}
  labels:
    app: {{ template "sumologic.labels.app.setup.configmap" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "conf/setup/*").AsConfig .) | nindent 2 }}
{{- end }}
