{{- if .Values.sumologic.setupEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  annotations:
{{ toYaml .Values.sumologic.setup.configMap.annotations | indent 4 }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "conf/setup/*").AsConfig .) | nindent 2 }}

{{- end }}