{{- if .Values.sumologic.setupEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sumologic.metadata.name.setup.job" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ include "sumologic.annotations.app.setup.helmsh" "3" | indent 4 }}
  labels:
    app: {{ template "sumologic.labels.app.setup.job" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
{{- if .Values.sumologic.podAnnotations }}
{{ toYaml .Values.sumologic.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.sumologic.setup.job.podAnnotations }}
{{ toYaml .Values.sumologic.setup.job.podAnnotations | indent 8 }}
{{- end }}
      labels:
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 8 }}
{{- end }}
{{- if .Values.sumologic.setup.job.podLabels }}
{{ toYaml .Values.sumologic.setup.job.podLabels | indent 8 }}
{{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "sumologic.metadata.name.setup.roles.serviceaccount" . }}
{{- if .Values.sumologic.setup.job.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sumologic.setup.job.nodeSelector | indent 8 }}
{{- end }}
      volumes:
      - name: setup
        configMap:
          name: {{ template "sumologic.metadata.name.setup.configmap" . }}
          defaultMode: 0777
      containers:
      - name: setup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/etc/terraform/setup.sh"]
        resources:
          {{- toYaml .Values.sumologic.setup.job.resources | nindent 10 }}
        volumeMounts:
        - name: setup
          mountPath: /etc/terraform
        {{- if .Values.sumologic.envFromSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.sumologic.envFromSecret }}
        {{ else }}
        env:
        - name: SUMOLOGIC_ACCESSID
          value: {{ required "A valid .Values.sumologic.accessId entry required!" .Values.sumologic.accessId }}
        - name: SUMOLOGIC_ACCESSKEY
          value: {{ required "A valid .Values.sumologic.accessKey entry required!" .Values.sumologic.accessKey }}
        - name: SUMOLOGIC_BASE_URL
          value: {{ .Values.sumologic.endpoint }}
        - name: HTTP_PROXY
          value: {{ .Values.sumologic.httpProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.sumologic.httpsProxy }}
        - name: NO_PROXY
          value: {{ .Values.sumologic.noProxy }}
        {{ end }}
      securityContext:
        runAsUser: 999
{{- end }}
