{{- if .Values.sumologic.setupEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sumologic.metadata.name.setup.job" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
{{- if .Values.sumologic.podAnnotations }}
{{ toYaml .Values.sumologic.podAnnotations | indent 2 }}
{{- end }}
  labels:
    app: {{ template "sumologic.labels.app.setup.job" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 4 }}
{{- end }}
{{- if .Values.sumologic.setup.job.podLabels }}
{{ toYaml .Values.sumologic.setup.job.podLabels | indent 4 }}
{{- end }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "sumologic.metadata.name.setup.roles.serviceaccount" . }}
      volumes:
      - name: setup
        configMap:
          name: {{ template "sumologic.metadata.name.setup.configmap" . }}
          defaultMode: 0777
      containers:
      - name: setup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/etc/terraform/setup.sh"]
        volumeMounts:
        - name: setup
          mountPath: /etc/terraform
        {{- if .Values.sumologic.envFromSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.sumologic.envFromSecret }}
        {{ else }}
        env:
        - name: SUMOLOGIC_ACCESSID
          value: {{ required "A valid .Values.sumologic.accessId entry required!" .Values.sumologic.accessId }}
        - name: SUMOLOGIC_ACCESSKEY
          value: {{ required "A valid .Values.sumologic.accessKey entry required!" .Values.sumologic.accessKey }}
        - name: SUMOLOGIC_BASE_URL
          value: {{ .Values.sumologic.endpoint }}
        - name: HTTP_PROXY
          value: {{ .Values.sumologic.httpProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.sumologic.httpsProxy }}
        {{ end }}
{{- end }}
