{{- if .Values.sumologic.setupEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{ template "sumologic.labels.common" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sumologic.fullname" . }}-setup
subjects:
  - kind: ServiceAccount
    name: {{ template "sumologic.fullname" . }}-setup
    namespace: {{ .Release.Namespace }}

{{- end }}