{{- if .Values.sumologic.setupEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "sumologic.metadata.name.setup.roles.serviceaccount" . }}
  annotations:
{{ toYaml .Values.sumologic.setup.serviceAccount.annotations | indent 4 }}
  labels:
    app: {{ template "sumologic.labels.app.roles.serviceaccount" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- end }}
