{{- if .Values.sumologic.setupEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{ template "sumologic.labels.common" . }}
{{- end }}