prometheus:
  prometheusSpec:
    externalLabels:
      # Set this to a value to distinguish between different k8s clusters
      cluster: kubernetes
    remoteWrite:
    # kube state metrics
    - url: http://fluentd:9888/prometheus.metrics.state.statefulset
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_statefulset_status_(?:observed_generation|replicas)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.statefulset
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_statefulset_(?:replicas|metadata_generation)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.daemonset
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_daemonset_status_(?:current_number_scheduled|desired_number_scheduled|number_misscheduled|number_unavailable)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.daemonset
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_daemonset_metadata_generation
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.deployment
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_deployment_(?:metadata_generation|spec_paused|spec_replicas|spec_strategy_rollingupdate_max_unavailable)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.deployment
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_deployment_status_(?:replicas_available|observed_generation|replicas_unavailable)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.node
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_node_(?:info|spec_unschedulable|status_allocatable|status_capacity|status_condition)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.pod
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_pod_container_(?:info|resource_requests|resource_limits|status_ready|status_terminated_reason|status_waiting_reason)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.pod
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;kube_pod_status_phase
        sourceLabels: [job, __name__]
    # controller manager metrics
    - url: http://fluentd:9888/prometheus.metrics.controller-manager
      writeRelabelConfigs:
      - action: keep
        regex: kube-controller-manager;cloudprovider_.*_api_request_duration_seconds.*
        sourceLabels: [job, __name__]
    # scheduler metrics
    - url: http://fluentd:9888/prometheus.metrics.scheduler
      writeRelabelConfigs:
      - action: keep
        regex: kube-scheduler;scheduler_(?:e2e_scheduling|binding|scheduling_algorithm)_latency_microseconds.*
        sourceLabels: [job, __name__]
    # api server metrics
    - url: http://fluentd:9888/prometheus.metrics.apiserver
      writeRelabelConfigs:
      - action: keep
        regex: apiserver;apiserver_request_(?:count|latencies.*)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.apiserver
      writeRelabelConfigs:
      - action: keep
        regex: apiserver;etcd_request_cache_(?:get|add)_latencies_summary.*
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.apiserver
      writeRelabelConfigs:
      - action: keep
        regex: apiserver;etcd_helper_cache_(?:hit|miss)_count
        sourceLabels: [job, __name__]
    # kubelet metrics
    - url: http://fluentd:9888/prometheus.metrics.kubelet
      writeRelabelConfigs:
      - action: keep
        regex: kubelet;kubelet_docker_operations_(?:errors|latency_microseconds.*)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.kubelet
      writeRelabelConfigs:
      - action: keep
        regex: kubelet;kubelet_(running_container_count|running_pod_count|runtime_operations_latency_microseconds.*)
        sourceLabels: [job, __name__]
    # cadvisor container metrics
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: drop
        regex: POD
        sourceLabels: [container]
      - action: drop
        regex: POD
        sourceLabels: [container_name]
      - action: keep
        regex: kubelet;container_cpu_(?:load_average_10s|(?:system|usage|cfs_throttled)_seconds_total)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: drop
        regex: POD
        sourceLabels: [container]
      - action: drop
        regex: POD
        sourceLabels: [container_name]
      - action: keep
        regex: kubelet;container_memory_(?:usage_bytes|memory_swap|working_set_bytes)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: drop
        regex: POD
        sourceLabels: [container]
      - action: drop
        regex: POD
        sourceLabels: [container_name]
      - action: keep
        regex: kubelet;container_spec_memory_(?:|swap|reservation)_limit_bytes
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: drop
        regex: POD
        sourceLabels: [container]
      - action: drop
        regex: POD
        sourceLabels: [container_name]
      - action: keep
        regex: kubelet;container_fs_(?:(?:usage|limit)_bytes|(?:reads|writes)_bytes_total)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: drop
        regex: POD
        sourceLabels: [container]
      - action: drop
        regex: POD
        sourceLabels: [container_name]
      - action: keep
        regex: kubelet;container_network_(?:receive|transmit)_(?:bytes|errors)_total
        sourceLabels: [job, __name__]
    # node exporter metrics
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_load(?:1|5|15)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_cpu_seconds_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_memory_(?:MemAvailable|MemTotal|Buffers|SwapCached|Cached|Free)_bytes
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_ipvs_(?:incoming|outgoing)_(?:bytes|packets)_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_disk_(?:(?:reads|writes)_completed|(?:read|written)_bytes)_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_filesystem_(?:avail|free|size)_bytes
        sourceLabels: [job, __name__]
    # prometheus operator rules
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: apiserver;cluster_quantile:apiserver_request_latencies:histogram_quantile
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: instance:node_(?:cpu|filesystem_usage|network_receive_bytes|node_network_transmit_bytes):rate:sum
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: instance:node_cpu:ratio|cluster:node_cpu:sum_rate5m|cluster:node_cpu:ratio
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: cluster_quantile:scheduler_(?:e2e_scheduling|scheduling_algorithm|binding)_latency:histogram_quantile
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: 'node_namespace_pod:kube_pod_info:|:kube_pod_info_node_count:'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: 'node:node_num_cpu:sum|:node_cpu_utilisation:avg1m|node:node_cpu_utilisation:avg1m|node:cluster_cpu_utilisation:ratio|:node_cpu_saturation_load1:|node:node_cpu_saturation_load1:'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: ':node_memory_utilisation:|:node_memory_MemFreeCachedBuffers_bytes:sum|:node_memory_MemTotal_bytes:sum|node:node_memory_bytes_available:sum|node:node_memory_bytes_total:sum|node:node_memory_utilisation:ratio|node:cluster_memory_utilisation:ratio|:node_memory_swap_io_bytes:sum_rate|node:node_memory_utilisation:|node:node_memory_utilisation_2:|node:node_memory_swap_io_bytes:sum_rate'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: ':node_disk_utilisation:avg_irate|node:node_disk_utilisation:avg_irate|:node_disk_saturation:avg_irate|node:node_disk_saturation:avg_irate'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: 'node:node_filesystem_usage:|node:node_filesystem_avail:'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: ':node_net_utilisation:sum_irate|node:node_net_utilisation:sum_irate|:node_net_saturation:sum_irate|node:node_net_saturation:sum_irate'
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.operator.rule
      writeRelabelConfigs:
      - action: keep
        regex: 'node:node_inodes_total:|node:node_inodes_free:'
        sourceLabels: [__name__]
    # up metrics
    - url: http://fluentd:9888/prometheus.metrics
      writeRelabelConfigs:
      - action: keep
        regex: up
        sourceLabels: [__name__]
