{{- if eq (include "metrics.fluentd.enabled" .) "true" }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sumologic.metadata.name.metrics.hpa" . }}
  labels:
    app: {{ template "sumologic.labels.app.metrics.hpa" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ template "sumologic.metadata.name.metrics.statefulset" . }}
  minReplicas: {{ .Values.fluentd.metrics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.fluentd.metrics.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.fluentd.metrics.autoscaling.targetCPUUtilizationPercentage }}
{{- if .Values.fluentd.metrics.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.fluentd.metrics.autoscaling.targetMemoryUtilizationPercentage }}
{{- end -}}
{{- end -}}
