{{- if eq (include "metrics.fluentd.enabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sumologic.metadata.name.metrics.service" . }}
  labels:
    app: {{ template "sumologic.labels.app.metrics.service" . }}
    {{- include "sumologic.labels.scrape.metrics" . | nindent 4 }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
{{- if .Values.fluentd.serviceLabels }}
{{ toYaml .Values.fluentd.serviceLabels | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ template "sumologic.labels.app.metrics.pod" . }}
  ports:
  - name: prom-write
    port: 9888
    targetPort: 9888
    protocol: TCP
  - name: metrics
    port: 24231
    targetPort: 24231
    protocol: TCP
{{- end }}
