{{- if .Values.sumologic.metrics.enabled -}}
{{- $serviceMonitors := concat .Values.sumologic.metrics.serviceMonitors .Values.sumologic.metrics.additionalServiceMonitors -}}
---
{{- if $serviceMonitors }}
apiVersion: v1
kind: List
items:
{{- range $serviceMonitors }}
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: {{ .name }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        app: {{ template "kube-prometheus-stack.name" $ }}-prometheus
{{ include "kube-prometheus-stack.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
      namespaceSelector:
        matchNames:
          - {{ template "kube-prometheus-stack.namespace" $ }}
      selector:
{{ toYaml .selector | indent 8 }}
    {{- if .targetLabels }}
      targetLabels:
{{ toYaml .targetLabels | indent 8 }}
    {{- end }}
    {{- if .podTargetLabels }}
      podTargetLabels:
{{ toYaml .podTargetLabels | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
