{{- if eq (include "events.fluentd.enabled" .) "true" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "sumologic.metadata.name.events.statefulset" . }}
  labels:
    app: {{ template "sumologic.labels.app.events.statefulset" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "sumologic.labels.app.events.pod" . }}
  serviceName: {{ template "sumologic.metadata.name.events.service-headless" . }}
  podManagementPolicy: "Parallel"
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/events/fluentd/configmap.yaml") . | sha256sum }}
{{- if .Values.sumologic.podAnnotations }}
{{ toYaml .Values.sumologic.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.fluentd.podAnnotations }}
{{ toYaml .Values.fluentd.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.fluentd.events.statefulset.podAnnotations }}
{{ toYaml .Values.fluentd.events.statefulset.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "sumologic.labels.app.events.pod" . }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
{{- if .Values.sumologic.podLabels }}
{{ toYaml .Values.sumologic.podLabels | indent 8 }}
{{- end }}
{{- if .Values.fluentd.podLabels }}
{{ toYaml .Values.fluentd.podLabels | indent 8 }}
{{- end }}
{{- if .Values.fluentd.events.statefulset.podLabels }}
{{ toYaml .Values.fluentd.events.statefulset.podLabels | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "sumologic.metadata.name.roles.serviceaccount" . }}
{{- if .Values.fluentd.events.statefulset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentd.events.statefulset.nodeSelector | indent 8 }}
{{- end }}
{{- if or .Values.fluentd.events.statefulset.affinity }}
      affinity:
{{ toYaml .Values.fluentd.events.statefulset.affinity | indent 8 }}
{{- end }}
{{- if .Values.fluentd.events.statefulset.tolerations }}
      tolerations:
{{ toYaml .Values.fluentd.events.statefulset.tolerations | indent 8 }}
{{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "sumologic.metadata.name.events.configmap" . }}
{{- if .Values.fluentd.events.extraVolumes }}
{{ toYaml .Values.fluentd.events.extraVolumes | indent 6 }}
{{- end }}
      securityContext:
        {{- toYaml .Values.fluentd.securityContext | nindent 8 }}
      {{- if .Values.fluentd.events.statefulset.priorityClassName }}
      priorityClassName: {{ .Values.fluentd.events.statefulset.priorityClassName | quote }}
      {{- end }}
{{- with .Values.fluentd.events.statefulset.initContainers }}
      initContainers:
      {{- if kindIs "string" . }}
        {{- tpl . $ | nindent 8 }}
      {{- else }}
        {{-  toYaml . | nindent 8 }}
      {{- end -}}
{{- end }}
      containers:
      - name: fluentd-events
        image: {{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}
        imagePullPolicy: {{ .Values.fluentd.image.pullPolicy }}
        resources:
          {{- toYaml .Values.fluentd.events.statefulset.resources | nindent 10 }}
        {{- if .Values.fluentd.events.statefulset.containers.fluentd.securityContext }}
        securityContext:
          {{- toYaml .Values.fluentd.events.statefulset.containers.fluentd.securityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
{{- if .Values.fluentd.persistence.enabled }}
        - name: buffer
          mountPath: "/fluentd/buffer"
{{- end}}
{{- if .Values.fluentd.events.extraVolumeMounts }}
{{ toYaml .Values.fluentd.events.extraVolumeMounts | indent 8 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 30
          periodSeconds: 5
        env:
{{- $ctx := .Values -}}
{{- include "kubernetes.sources.envs" (dict "Context" $ctx "Type" "events") -}}
{{- if .Values.fluentd.events.extraEnvVars }}
{{ toYaml .Values.fluentd.events.extraEnvVars | nindent 8 }}
{{- end }}
{{- if .Values.fluentd.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: buffer
{{- if .Values.fluentd.pvcLabels }}
      labels:
{{ toYaml .Values.fluentd.pvcLabels | indent 8 }}
{{- end }}
    spec:
      accessModes: [{{ .Values.fluentd.persistence.accessMode }}]
      storageClassName: {{ .Values.fluentd.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.fluentd.persistence.size }}
{{- end }}
{{- end }}
